"""Constantes del simulador de torneos. Nada de valores sueltos en el código."""

CANTIDAD_LUCHADORES_ROSTER = 12
CANTIDAD_LUCHADORES_TORNEO = 8

DANIO_MINIMO = 1
MULTIPLICADOR_CRITICO = 2
PROBABILIDAD_DESEMPATE_VELOCIDAD = 0.5

MILISEGUNDOS_POR_SEGUNDO = 1000
SEMILLA_MAXIMA = 2**32
